moduleRoots:
  - ../node_modules
dependencies:
  #- 'lodash/trimEnd'
  #- 'lodash.trimend/index.js'
  - '@babel/runtime/helpers/interopRequireDefault'
  - '@babel/runtime/helpers/interopRequireWildcard'
  - '@babel/runtime/helpers/createClass'
  - '@babel/runtime/helpers/classCallCheck'
  - '@babel/runtime/helpers/defineProperty'
  #- '@babel/runtime/helpers/asyncToGenerator'
  #- '@babel/runtime/regenerator'
